version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: preprint_db
      POSTGRES_USER: preprint
      POSTGRES_PASSWORD: preprint
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: ["sh", "-c", "until nc -z db 5432; do echo 'Waiting for database...'; sleep 2; done; echo 'Database ready!'; npm start"]
    environment:
      - DATABASE_USER=preprint
      - DATABASE_PASSWORD=preprint
      - DATABASE_HOST=db
      - DATABASE_NAME=preprint_db
      - DATABASE_PORT=5432
      - CORS_URL=["http://localhost:3000"]
    ports:
      - "9000:9000"
    volumes:
      - pdfs:/usr/src/app/uploads
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:9000
    ports:
      - "3000:80"
    depends_on:
      - backend

  grobid:
    image: lfoppiano/grobid:0.8.0
    
  latex-render:
    image: vsfexperts/latex-render-server
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  postgres_data:
  pdfs:
