name: ci
on:
  push:
    branches:
      - main
jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: frontend/.
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:latest

      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: backend/.
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:latest
