name: ci
on:
  push:
    branches:
      - main
jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontent
        uses: docker/build-push-action@v2
        with:
          context: frontend/.
          push: true
          tags: lkaesberg/citeassist-frontend:latest
      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: backend/.
          push: true
          tags: lkaesberg/citeassist-backend:latest
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
